/**
 * Demo storefront data — generic home & garden goods so the shop can be seen
 * end-to-end before real supplier data arrives. Every record is flagged
 * `isDemoData: true`, is shown with a DEMO watermark in the admin, and is
 * never a pest-control product.
 */
export interface DemoProductSeed {
  slug: string
  name: string
  shortDescription: string
  description: string
  benefits: string[]
  suitableFor: string[]
  categorySlugs: string[]
  primaryCategorySlug: string
  /** agorot */
  price: number
  salePrice?: number
  costPrice?: number
  stock: number
  isBestSeller?: boolean
  isNew?: boolean
  poisonFree?: boolean
  keywords: string[]
  /** Hue used to render the branded placeholder image. */
  placeholderHue: number
}

export const DEMO_PRODUCTS: DemoProductSeed[] = [
  {
    slug: 'demo-modular-storage-box-12l',
    name: 'קופסת אחסון מודולרית 12 ליטר',
    shortDescription: 'קופסה שקופה עם מכסה נצמד, נערמת לגובה.',
    description: 'קופסת אחסון מודולרית לארון, למחסן ולמזווה. המכסה נסגר בקליק והקופסאות נערמות זו על זו בלי לאבד יציבות.',
    benefits: ['נערמת לגובה', 'מכסה נצמד', 'חומר שקוף שמאפשר לזהות תכולה'],
    suitableFor: ['ארון בגדים', 'מזווה', 'מחסן'],
    categorySlugs: ['organization', 'storage', 'boxes'],
    primaryCategorySlug: 'storage',
    price: 4900,
    costPrice: 2600,
    stock: 48,
    isBestSeller: true,
    keywords: ['אחסון', 'קופסה', 'ארגון'],
    placeholderHue: 205,
  },
  {
    slug: 'demo-kitchen-drawer-organizer',
    name: 'ארגונית מגירה למטבח',
    shortDescription: 'מחיצות מתכווננות לסכו״ם ולכלי מטבח.',
    description: 'ארגונית מגירה עם מחיצות מתכווננות שמתאימה את עצמה לרוחב המגירה ושומרת על סדר בסכו״ם ובכלים הקטנים.',
    benefits: ['מחיצות מתכווננות', 'בסיס מונע החלקה', 'ניקוי בשטיפה'],
    suitableFor: ['מגירת מטבח', 'מגירת משרד'],
    categorySlugs: ['organization', 'organizers', 'kitchen'],
    primaryCategorySlug: 'organizers',
    price: 7900,
    salePrice: 5900,
    costPrice: 3400,
    stock: 31,
    isBestSeller: true,
    keywords: ['מטבח', 'ארגונית', 'מגירה'],
    placeholderHue: 32,
  },
  {
    slug: 'demo-bathroom-shelf-basket',
    name: 'סלסלת מדף לאמבטיה',
    shortDescription: 'סלסלה מאווררת עם ידיות, מתאימה למדף ולארון.',
    description: 'סלסלת אחסון מאווררת לחדר הרחצה. הידיות מאפשרות להוציא את כל התכולה במכה אחת, והחורים מונעים הצטברות לחות.',
    benefits: ['מאווררת', 'ידיות נשיאה', 'עמידה בלחות'],
    suitableFor: ['ארון אמבטיה', 'מדף כביסה'],
    categorySlugs: ['organization', 'baskets', 'bathroom'],
    primaryCategorySlug: 'baskets',
    price: 3500,
    costPrice: 1700,
    stock: 64,
    isNew: true,
    keywords: ['אמבטיה', 'סלסלה', 'אחסון'],
    placeholderHue: 190,
  },
  {
    slug: 'demo-pedal-bin-30l',
    name: 'פח דוושה 30 ליטר',
    shortDescription: 'פח דוושה עם דלי פנימי נשלף וסגירה שקטה.',
    description: 'פח דוושה למטבח עם דלי פנימי נשלף להחלפת שקית מהירה ומנגנון סגירה שקט.',
    benefits: ['סגירה שקטה', 'דלי פנימי נשלף', 'בסיס יציב'],
    suitableFor: ['מטבח', 'חדר שירות'],
    categorySlugs: ['cleaning', 'bins', 'kitchen'],
    primaryCategorySlug: 'bins',
    price: 14900,
    costPrice: 8200,
    stock: 12,
    keywords: ['פח', 'מטבח', 'ניקיון'],
    placeholderHue: 220,
  },
  {
    slug: 'demo-garden-hose-25m',
    name: 'צינור השקיה 25 מטר',
    shortDescription: 'צינור גמיש עם חיבורים מהירים לברז ולמזלף.',
    description: 'צינור השקיה לגינה ולחצר באורך 25 מטר, כולל חיבורים מהירים לברז ולמזלף.',
    benefits: ['גמיש גם בקור', 'חיבורים מהירים', 'עמיד ב-UV'],
    suitableFor: ['גינה', 'חצר', 'מרפסת'],
    categorySlugs: ['garden', 'irrigation'],
    primaryCategorySlug: 'irrigation',
    price: 12900,
    salePrice: 9900,
    costPrice: 6100,
    stock: 22,
    isBestSeller: true,
    keywords: ['השקיה', 'גינה', 'צינור'],
    placeholderHue: 140,
  },
  {
    slug: 'demo-garden-tool-set-5',
    name: 'סט כלי גינון 5 חלקים',
    shortDescription: 'כף, מזמרה, מגרפה, מזלג וכלי שתילה בתיק נשיאה.',
    description: 'סט כלי גינון ביתי בחמישה חלקים עם ידיות ארגונומיות ותיק נשיאה מתקפל.',
    benefits: ['ידיות ארגונומיות', 'פלדת אל-חלד', 'תיק נשיאה'],
    suitableFor: ['גינה', 'עציצים', 'מרפסת'],
    categorySlugs: ['garden', 'garden-tools'],
    primaryCategorySlug: 'garden-tools',
    price: 17900,
    costPrice: 9800,
    stock: 18,
    isNew: true,
    keywords: ['גינון', 'כלים', 'גינה'],
    placeholderHue: 96,
  },
  {
    slug: 'demo-bbq-tool-set',
    name: 'סט כלים למנגל 4 חלקים',
    shortDescription: 'מלקחיים, מרית, מברשת ומזלג מפלדת אל-חלד.',
    description: 'סט כלי מנגל בעל ידיות ארוכות שמרחיקות את היד מהגחלים, מפלדת אל-חלד שניתנת לשטיפה.',
    benefits: ['ידיות ארוכות', 'פלדת אל-חלד', 'תלייה נוחה'],
    suitableFor: ['מנגל', 'חצר', 'קמפינג'],
    categorySlugs: ['garden', 'bbq'],
    primaryCategorySlug: 'bbq',
    price: 9900,
    costPrice: 5200,
    stock: 27,
    keywords: ['מנגל', 'bbq', 'חצר'],
    placeholderHue: 18,
  },
  {
    slug: 'demo-spice-rack-stand',
    name: 'מעמד תבלינים מדורג',
    shortDescription: 'שלוש מדרגות שמציגות את כל הצנצנות במבט אחד.',
    description: 'מעמד תבלינים מדורג לארון או לשיש. שלוש המדרגות מציגות את כל הצנצנות בשורה אחת בלי לחפש.',
    benefits: ['שלוש מדרגות', 'בסיס מונע החלקה', 'מתאים גם לארון עמוק'],
    suitableFor: ['ארון מטבח', 'משטח עבודה'],
    categorySlugs: ['organization', 'stands', 'kitchen'],
    primaryCategorySlug: 'stands',
    price: 5900,
    costPrice: 2900,
    stock: 40,
    keywords: ['תבלינים', 'מעמד', 'מטבח'],
    placeholderHue: 45,
  },
  {
    slug: 'demo-under-sink-organizer',
    name: 'ארגונית מתחת לכיור',
    shortDescription: 'מדף מתכוונן שעוקף את הצנרת ומכפיל שטח אחסון.',
    description: 'ארגונית מתכווננת לארון שמתחת לכיור. רגליים מתכווננות מאפשרות לעקוף את הצנרת ולנצל את כל גובה הארון.',
    benefits: ['רגליים מתכווננות', 'עוקף צנרת', 'הרכבה ללא כלים'],
    suitableFor: ['מטבח', 'אמבטיה'],
    categorySlugs: ['organization', 'organizers', 'bathroom'],
    primaryCategorySlug: 'organizers',
    price: 8900,
    salePrice: 6900,
    costPrice: 4100,
    stock: 0,
    keywords: ['כיור', 'ארגונית', 'אחסון'],
    placeholderHue: 260,
  },
  {
    slug: 'demo-stackable-shoe-box',
    name: 'קופסת נעליים נערמת',
    shortDescription: 'דלת קדמית שנפתחת בלי לפרק את הערימה.',
    description: 'קופסת נעליים שקופה עם דלת קדמית, כך שניתן להוציא זוג מהתחתית בלי לפרק את כל הערימה.',
    benefits: ['דלת קדמית', 'נערמת', 'מאווררת'],
    suitableFor: ['ארון', 'מבואה'],
    categorySlugs: ['organization', 'storage', 'boxes'],
    primaryCategorySlug: 'boxes',
    price: 2900,
    costPrice: 1300,
    stock: 120,
    isBestSeller: true,
    keywords: ['נעליים', 'אחסון', 'ארגון'],
    placeholderHue: 300,
  },
  {
    slug: 'demo-laundry-basket-foldable',
    name: 'סל כביסה מתקפל',
    shortDescription: 'מתקפל לרוחב של 6 ס״מ כשלא בשימוש.',
    description: 'סל כביסה עם שלד מתקפל וידיות בד. כשלא בשימוש הוא מתקפל ונכנס בין המכונה לקיר.',
    benefits: ['מתקפל', 'ידיות בד', 'קל לניקוי'],
    suitableFor: ['חדר כביסה', 'אמבטיה', 'חדר שינה'],
    categorySlugs: ['organization', 'baskets', 'home'],
    primaryCategorySlug: 'baskets',
    price: 6900,
    costPrice: 3300,
    stock: 35,
    keywords: ['כביסה', 'סל', 'מתקפל'],
    placeholderHue: 168,
  },
  {
    slug: 'demo-door-seal-strip',
    name: 'סרט אטימה לדלת',
    shortDescription: 'אוטם את הרווח התחתון ומונע כניסת חרקים ואבק.',
    description: 'סרט סיליקון להדבקה בתחתית הדלת. אוטם את הרווח שמתחת לדלת ומונע כניסת אבק, לכלוך וחרקים זוחלים.',
    benefits: ['הדבקה עצמית', 'ניתן לחיתוך לפי רוחב', 'ללא חומרים כימיים'],
    suitableFor: ['דלת כניסה', 'דלת מרפסת', 'מחסן'],
    categorySlugs: ['home', 'pest-prevention', 'poison-free'],
    primaryCategorySlug: 'home',
    price: 4500,
    costPrice: 1900,
    poisonFree: true,
    stock: 80,
    isNew: true,
    keywords: ['אטימה', 'דלת', 'מניעה', 'ללא רעל'],
    placeholderHue: 12,
  },
]
